### ISSUE TITLE
KeyError: tensor(507764)

### ISSUE THREAD

**Issue by yongbowin** [microsoft/MSMARCO-Question-Answering#4]
Another error occurs when I run `predict.py`, the error information as following:
```
Loading Model...
/home/wangyongbo/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Augmenting with random embeddings...
Augmenting with random char embeddings...
Traceback (most recent call last):
  File "/DATA2/wangyongbo/ms_marco/MSMARCO-Question-Answering/Baseline/experiment/predict.py", line 202, in <module>
    main()
  File "/DATA2/wangyongbo/ms_marco/MSMARCO-Question-Answering/Baseline/experiment/predict.py", line 186, in main
    toks = regex_multi_space.sub(' ', regex_drop_char.sub(' ', ' '.join(id_to_token[tok] for tok in toks).lower())).strip()
  File "/DATA2/wangyongbo/ms_marco/MSMARCO-Question-Answering/Baseline/experiment/predict.py", line 186, in <genexpr>
    toks = regex_multi_space.sub(' ', regex_drop_char.sub(' ', ' '.join(id_to_token[tok] for tok in toks).lower())).strip()
KeyError: tensor(507764)
```
The running script is following:
```
#!/bin/bash
export CUDA_VISIBLE_DEVICES=1

export MS_PATH=/DATA2/wangyongbo/ms_marco/MSMARCO-Question-Answering/Baseline/experiment

python3 $MS_PATH/predict.py $MS_PATH/ $MS_PATH/data/dev_v2.1.json prediction.json --cuda=True
```

**Comment by yongbowin** [comment]
Modify #4 with submission #5 , the inspiration come from [@leejincheng](https://github.com/leejincheng) answer in [第十章图像描述中model.py和main.py的问题 #93](https://github.com/chenyuntc/pytorch-book/issues/93#issuecomment-421729838).
